export const environment = {
	production: false,
	cloudinaryBaseUrl: 'https://res.cloudinary.com/whydonate/image/upload/',
	apiUrl: 'https://whydonate-development.appspot.com/api/v1/',
	ACCOUNT_API_V2: 'https://account-features.whydonate.workers.dev/',
	ACCOUNTING_API: 'https://accounting-features.whydonate.workers.dev/',
	DONATION_API_V2: 'https://donation-features.whydonate.workers.dev/',
	FUNDRAISER_API_V2: 'https://fundraiser-features.whydonate.workers.dev/',
	homeUrl: 'https://whydonate.in',
	helpDeskUrl: 'https://helpdesk.whydonate.com',
	domain: 'whydonate.in',
	donation_url: 'https://donation-features.whydonate.workers.dev',
	wallet_url: 'https://wallet-features.whydonate.workers.dev/',
	project_url: 'https://project-features.whydonate.workers.dev/',
	search_url: 'https://search-features.whydonate.workers.dev/',
	fundraiser_url: 'https://fundraiser-features.whydonate.workers.dev/',
	fundraiser_features_url: 'https://fundraiser-features.whydonate.workers.dev/',
};
