export const environment = {
	production: true,
	zaraz: '',
	cloudinaryBaseUrl: 'https://res.cloudinary.com/whydonate/image/upload/',
	apiUrl: 'https://whydonate-production-api.appspot.com/api/v1/',
	// ACCOUNT_API_V2: 'https://account-master.whydonate.workers.dev/',
	ACCOUNT_API_V2: 'https://account-master.whydonate.dev/',
	ACCOUNTING_API: 'https://accounting-master.whydonate.dev/',
	// DONATION_API_V2: 'https://donation-master.whydonate.workers.dev/',
	DONATION_API_V2: 'https://donation-master.whydonate.dev/',
	FUNDRAISER_API_V2: 'https://fundraiser-master.whydonate.dev/',
	homeUrl: 'http://master.whydonate-web-portal.pages.dev',
	helpDeskUrl: 'https://helpdesk.whydonate.com',
	domain: 'whydonate.in',
	donation_url: 'https://donation-master.whydonate.dev',
	wallet_url: 'https://wallet-master.whydonate.dev/',
	project_url: 'https://project-master.whydonate.dev/',
	search_url: 'https://search-master.whydonate.dev/',
	fundraiser_url: 'https://fundraiser-master.whydonate.dev/',
	fundraiser_features_url: 'https://fundraiser-master.whydonate.dev/',
};
